---

 # Set (httpd_can_network_connect) flag on and keep it persistent across reboots
 - seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes

 - file:
    path: /var/www/webmail
    state: directory

 - copy:
    dest: /etc/httpd/conf.d/webmail.conf
    src: httpd/webmail.conf
    owner: root
    group: root
   become: true

 - name: testing roundcube push
   unarchive: src=webmail/roundcubemail-1.3.1-complete.tar.gz dest=/tmp/ owner=sgoodliff
   become: true

 - name: test synchronize
   synchronize: 
    src: /tmp/roundcubemail-1.3.1/
    dest: /var/www/webmail/

 - file:
    path: "/var/www/webmail/{{ item }}"
    owner: apache
    group: apache
   with_items:
    - temp
    - logs

 - name: copy roundcube config out
   copy:
    src: webmail/config.inc.php
    dest: /var/www/webmail/config/

 - name: roundcube tidy cron
   cron: minute=0 hour=0 weekday=0 job="cleandb.sh" user=sgoodliff

